### PR TITLE
Bump v0.1.3

### LINKED ISSUE #10: Segfault on macOS
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running this code segfaults when creating the index:
```python
import numpy as np
from pys2index import S2PointIndex

latlon_points = np.array([[40.0, 15.0], 
                          [-20.0, 53.0], 
                          [81.0, 153.0]])

index = S2PointIndex(latlon_points)
```

### Installed packages

```shell
# packages in environment at /Users/rmay/miniconda3/envs/test-xarray:
#
# Name                    Version                   Build  Channel
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cftime                    1.6.1           py310h1bbcd0e_0    conda-forge
curl                      7.83.1               h23f1065_0    conda-forge
debugpy                   1.6.0           py310h9d931ec_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_h0aa1fa2_104    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   8.4.0           py310h2ec42d9_0    conda-forge
jedi                      0.18.1          py310h2ec42d9_1    conda-forge
jpeg                      9e                   hac89ed1_2    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.10.0          py310h2ec42d9_0    conda-forge
krb5                      1.19.3               hb98e516_0    conda-forge
libblas                   3.9.0           15_osx64_openblas    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libcurl                   7.83.1               h23f1065_0    conda-forge
libcxx                    14.0.6               hce7ea42_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libnetcdf                 4.8.1           nompi_h6609ca0_102    conda-forge
libnghttp2                1.47.0               hca56917_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               hd3787cc_2    conda-forge
libzip                    1.9.2                hedeed6f_0    conda-forge
libzlib                   1.2.12               hfe4f2af_2    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.0           nompi_py310hc1a5e9b_100    conda-forge
numpy                     1.23.1          py310ha3f357c_0    conda-forge
openssl                   3.0.5                hfe4f2af_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310h3099161_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.1.2             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1           py310h6c45266_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pys2index                 0.1.2           py310h509978a_2    conda-forge
python                    3.10.5          hdd68b96_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyzmq                     23.2.0          py310h85fb675_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
s2geometry                0.9.0                h45d4a6f_4    conda-forge
setuptools                63.2.0          py310h2ec42d9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.1               hd9f0692_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tornado                   6.2             py310h6c45266_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.6.0rc1.dev45+g89756bb7           dev_0    <develop>
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zlib                      1.2.12               hfe4f2af_2    conda-forge
```

### Environment info

```shell
active environment : test-xarray
    active env location : /Users/rmay/miniconda3/envs/test-xarray
            shell level : 1
       user config file : /Users/rmay/.condarc
 populated config files : /Users/rmay/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.10.5.final.0
       virtual packages : __osx=12.4=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/rmay/miniconda3  (writable)
      conda av data dir : /Users/rmay/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/rmay/miniconda3/pkgs
                          /Users/rmay/.conda/pkgs
       envs directories : /Users/rmay/miniconda3/envs
                          /Users/rmay/.conda/envs
               platform : osx-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.10.5 Darwin/21.5.0 OSX/12.4
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #10.

Closes #10.

Here's a checklist to do before merging.
- ~~Bump the build number if needed.~~
- [x] Bump version number
- [x] Reset the build number

### CODE REVIEW

**Comment by dopplershift** [comment]
Ok, this seems like it's beyond simple package version incompatibilities.

I think the test I added here would be useful to catch any future problems.

**Comment by benbovy** [comment]
> I think the test I added here would be useful to catch any future problems.

Thanks, that is useful indeed! It's not the fist time the library compiles fine and fails at runtime.

I've tried building pys2index locally and can reproduce the issue with numpy 1.19 or 1.22, while the tests are passing with numpy 1.21 (xtensor 0.24.1, xtensor python 0.26.0). That's weird.

**Comment by benbovy** [comment]
Looks like https://github.com/benbovy/pys2index/pull/5 fixed it.

Thanks again for the test @dopplershift.

**Comment by dopplershift** [comment]
Sweet, thanks for the fix!

**Pull request merged**
